export const projects = [
  {
    title: 'Kannappa',
    director: 'Mukesh Kumar Singh',
    writers: ['Vishnu Manchu', 'Gopalakrishna Paruchuri', 'G. Eshwar Reddy'],
    stars: ['Vishnu Manchu', 'Mohanlal', 'Prabhas'],
    producer: 'Mohan Babu',
    music: 'Stephen Devassy',
    cinematography: 'Sheldon Chau',
    editing: 'Anthony Gonsalves',
    description:
      'An atheist hunter Kannappa becomes a devotee of Lord Shiva and plucked out his eyes in an act of devotion.',
    year: 2024,
  },
  {
    title: 'Star',
    director: 'Elan',
    writers: ['Elan', 'Thava Guru'],
    stars: ['Kavin Lal', 'Aditi Sudhir Pohankar', 'Preity Mukhundhan'],
    cast: 'Meera Malarkodi',
    producers: [
      'Sagar Pentela',
      'BVSN Prasad',
      'Sreenidhi Sagar',
      'Raja Subrahmaniam',
      'P. Rupak Pranav Tej',
      'S. Vinod Kumar',
    ],
    music: 'Yuvan Shankar Raja',
    cinematography: 'Ezhil Arasu K.',
    editing: 'Pradeep E. Ragav',
    description:
      "Follows a youngster Kalai and his aspirations of becoming a 'Star' in the Tamil Film Industry. Born in a lower-middle-class family, will Kalai overcome all his struggles to emerge as a Star?",
    year: 2024,
  },
  {
    title: 'Om Bheem Bush',
    director: 'Sree Harsha Konuganti',
    writers: ['Manohar Bollam', 'Sree Harsha Konuganti'],
    stars: [
      'Ansari',
      'Mukku Avinash',
      'Spandana Bhandari',
      'Preity Mukhundhan',
    ],
    cast: 'Jalaja',
    producers: ['Sunil Balusu', 'V. Vamsi Krishna Reddy', 'Jagadish Talasila'],
    music: 'Sunny M.R.',
    cinematography: 'Raj Thota',
    editing: 'Vijay Vardhan',
    description:
      "Follows three scientists who come to a village to find a treasure, but things don't turn easy for them because there is black magic in that village.",
    year: 2024,
  },
  {
    title: 'Maine Pyar Kiya',
    director: 'Faizal Faziludeen',
    editing: 'Kannan Mohan',
    stars: ['Preity Mukhundhan'],
    producer: 'Sanju S. Unnithan',
    music: 'Ajmal Hasbulla',
    cinematography: 'Don Paul',
    writers: ['Faizal Faziludeen', 'Blk Fzl'],
    year: 2024,
  },
];
